python-interpreter-path = "python/.venv/Scripts/python.exe"
site-package-path = ["python/.venv/Lib/site-packages"]
search_path = [
    "ModelProvider",
    "Pipeline",
    "Tools",
    "Backend",
    "python",

    "Pipeline/openchad/chat",
    "Backend/openchad/litellm",
    "Backend/openchad/llamacpp",
    "ModelProvider/openchad/ProxyModelProvider",
    "ModelProvider/openchad/LocalModelProvider",
    "ModelProvider/openchad/LiteLLMModelProvider"
]
extraPaths = [
    "ModelProvider",
    "Pipeline",
    "Tools",
    "Backend",
    "python",

    "Pipeline/openchad/chat",
    "Backend/openchad/litellm",
    "Backend/openchad/llamacpp",
    "ModelProvider/openchad/ProxyModelProvider",
    "ModelProvider/openchad/LocalModelProvider",
    "ModelProvider/openchad/LiteLLMModelProvider"
]
